SELECT NAME_OF_EMPLOYEE, PHONE, DATE_OF_BIRTH, CITY, NAME_OF_COMPANY FROM EMPLOYEE_DATA INNER JOIN EMPLOYERS ON EMPLOYERS.ID = EMPLOYEE_DATA.ID;

SELECT NAME_OF_EMPLOYEE, PHONE, NAME_OF_COMPANY, SALARY FROM EMPLOYEE_DATA INNER JOIN EMPLOYERS ON EMPLOYERS.ID = EMPLOYEE_DATA.ID INNER JOIN VACANCYS ON VACANCYS.ID = EMPLOYERS.ID WHERE SALARY > 2000;

SELECT NAME_OF_EMPLOYEE, NAME_OF_UNIVERSITY, TYPE_OF_EDUCATION FROM EMPLOYEE_DATA INNER JOIN EDUCATION USING (id); 

SELECT NAME_OF_VACANCY, VACANCY_POSITION, COMPANY, SALARY, CONTACT_PERSON FROM VACANCYS INNER JOIN PERSON_TO_CONTACT ON PERSON_TO_CONTACT.ID = VACANCYS.ID INNER JOIN EMPLOYEE_DATA ON EMPLOYEE_DATA.ID = VACANCYS.ID WHERE DATE_OF_BIRTH > '01.01.1995';

